dubbo:
  #dubbo 启动端口号
  protocol:
    port: 20883
  registry:
    address: zookeeper://127.0.0.1:2181

spring:
  datasource:
    url: jdbc:mysql://192.168.3.171:3307/ucloud_crm_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver