
server:
  servlet:
    context-path: /parkapi
spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
dubbo:
  application:
    logger: slf4j
    name: consumer-webapi
  consumer:
    version: 1.0.0
    timeout: 10000